### ISSUE TITLE
Checkbox Text word wrap

### ISSUE THREAD

**Issue by MikeGWem** [IgnaceMaes/MaterialSkin#101]
Web based Material Design supports lengthy text labels for checkboxes and thus makes (passive?) provision for word wrap. It may or may not make any sense to support that within the context and objectives of this Windows Forms MD implementation project. 

As my project provided a "preview" facility I wanted to make the output of that preview fairly consistent across platforms. I have thus made a stab at implementing an optional word wrap attribute for MaterialCheckBox. This required quite a few changes and as this is a work in progress my code is likely to break with some edge cases. Like the current mainstream version, I have not provided any support for the base TextAlign property.

If anyone is interested in word wrap then let me know and I will let you have the code changes so you can give it a try.

**Comment by IgnaceMaes** [comment]
Feel free to open a pull request.

I'm going to close this because it isn't exactly an issue.
