### ISSUE TITLE
does this project still in development?

### ISSUE THREAD

**Issue by rqx110** [IgnaceMaes/MaterialSkin#103]
does this project still in development?

**Comment by QuantumRevenger** [comment]
It seems to be dead, I am looking whether you can theme WinForms with Xaml. 

https://github.com/ButchersBoy/MaterialDesignInXamlToolkit

**Comment by IgnaceMaes** [comment]
MaterialSkin is not in active development. However, I do look at pull requests and spent some time on the project every now and then.
