### ISSUE TITLE
Custom back color for theme

### ISSUE THREAD

**Issue by Wbdn** [IgnaceMaes/MaterialSkin#105]
Is there any way to change back color?

**Comment by SaitDev** [comment]
Yes. 

> materialSkinManager = MaterialSkinManager.Instance;
> materialSkinManager.ColorScheme = new ColorScheme(Primary.Blue400, Primary.LightBlue800, Primary.BlueGrey400,Accent.LightBlue400, TextShade.WHITE);

Color list can be found [here ](https://github.com/IgnaceMaes/MaterialSkin/blob/master/MaterialSkin/ColorScheme.cs#L87)
