### ISSUE TITLE
Change the font listview

### ISSUE THREAD

**Issue by lucasdavidferrero** [IgnaceMaes/MaterialSkin#106]
I have this problem guys 
![2016-06-03 22_25_52-clipboard](https://cloud.githubusercontent.com/assets/15804058/15796718/2bcf85e8-29da-11e6-9ae4-87bf8d8c1efb.jpg)
Its looks bad. It occurs just in the listview

**Comment by Wootness** [comment]
Do you have the Roboto font family installed on your system? I had a font related issue myself (#74) and installing the font fixed it.

**Comment by lucasdavidferrero** [comment]
@Wootness Yes, the font Roboto is installed in my system.
