### ISSUE TITLE
materialSingleLineTextField Focus & Select Don't Work

### ISSUE THREAD

**Issue by brunominervino** [IgnaceMaes/MaterialSkin#108]
I'm trying to use control.Select() or control.Focus() and don't work.

**Comment by SaitDev** [comment]
@brunominervino  Try my pull request, it should fix your problem

**Comment by brunominervino** [comment]
@SaitDev thank you! I'll try.

**Comment by lucasdavidferrero** [comment]
@SaitDev It works well, thanks!
