### ISSUE TITLE
Cursor turns into "MoveAll" cursor while over any Material Skin controls

### ISSUE THREAD

**Issue by jumper77** [IgnaceMaes/MaterialSkin#114]
This is something new. It started happening about 3 days ago and I have been trying to solve the issue for that long now. The mouse cursor was fine before this. In case it was a Visual Studio thing, I reset all the settings to default. But it did nothing. I've added and and re-added the dll and plus removed it's items from the toolbox, but again, nothing.

Has anyone seen or heard of this happening before?
Any help greatly appreciated.

**Comment by pernicek** [comment]
Recently I reported another issue, but cursor  behaves correctly. I think, that there must be some line in your code like

```
Control.Cursor = ..
Form.Cursor = .. 
```

In case there's not in your code - check form.designer files also - you can try to download source from here, check if there's something above and recompile and add it to your project.

**Comment by jumper77** [comment]
Thanks for the reply. I don't have any reference to "cursor" in my code, but I will check the designer file and see if I can find anything odd. Will let you know something in a bit.

**Comment by jumper77** [comment]
ok, didn't find anything out of place in the designer file, but I tried something else. I put a standard VS label on the form and it does the same thing as the Material controls do. Have more checking to do.

**Comment by jumper77** [comment]
Found out this is not a MaterialSkin issue. It's a Visual Studio issue. So I'm going in that direction. Thanks for looking and helping.

**Comment by IgnaceMaes** [comment]
I'm closing this because it's a Visual Studio related problem, not MaterialSkin.

**Comment by jumper77** [comment]
Thanks. Quick question. Is there some place where I can read about using the tab control?

**Comment by IgnaceMaes** [comment]
Luke Skinner explained the use very well in this post: https://github.com/IgnaceMaes/MaterialSkin/issues/41#issuecomment-90669808

**Comment by jumper77** [comment]
thank you
