### ISSUE TITLE
Clicked Event for TabControl

### ISSUE THREAD

**Issue by muscaiu** [IgnaceMaes/MaterialSkin#117]
I want to refresh some things when the user navigates to a specific Tab. 

Is it possbile to get Clicked Event for clicking on each specific TabControl?

**Comment by lucasdavidferrero** [comment]
Hi, you can use the Selecting event of materialTabControl.
Here a example:

`private void tabControlTurnos_Selecting(object sender, TabControlCancelEventArgs e)
        {
            if (e.TabPageIndex==1)
            {
                MessageBox.Show("hello!");
              
            }
        }`
The TabPageIndex is a specefic tab, can be 0,1,2... like a array.

**Comment by muscaiu** [comment]
Thanks  @lucasdavidferrero ! That's just what i was looking for.
