### ISSUE TITLE
Open or Close tabpage

### ISSUE THREAD

**Issue by baxi2990** [IgnaceMaes/MaterialSkin#122]
Hi good morning , there is some way that can create new tabs and close at runtime?

**Comment by IgnaceMaes** [comment]
Just like you would with a normal TabControl. Here's an example:
`var runtimeTabPage = new TabPage("Runtime TabPage");
            runtimeTabPage.BackColor = Color.White;

            var runtimeButton = new MaterialRaisedButton();
            runtimeButton.Text = "Added at runtime";
            runtimeTabPage.Controls.Add(runtimeButton);

            materialTabControl1.TabPages.Add(runtimeTabPage);`

And to delete:
`materialTabControl1.TabPages.Remove(runtimeTabPage);`
