### ISSUE TITLE
TabControl not Working

### ISSUE THREAD

**Issue by xJoeyv** [IgnaceMaes/MaterialSkin#128]
Hi,

My tab control doesn't work and keeps remain windows default! I used the installation instructions on the readme file. The Tab controls becomes default winform control and doesn't show up!

**Comment by Dutchs** [comment]
Hey xJoeyv,

I assume you ment it shows up as the WinForms TabControl in the designer and invisible during runtime?
You are probably missing the MaterialTabSelector with its BaseTabControl property set to the MaterialTabControl.

The MaterialSkinExample project has an example of it.

**Comment by xJoeyv** [comment]
Aswell in the designer as when I debug the application it shows as a default winforms thing. I will check the example! Thanks.

Else any more help is highly appreciated
