### ISSUE TITLE
is development on this going to continue? several issues.

### ISSUE THREAD

**Issue by agonzalezm** [IgnaceMaes/MaterialSkin#148]
First, this controls look great but i am not confident to use them in a new application.

I downloaded nuget package and there are many issues:

- TabControl is not working and doesnt show TabPages
- You cant drag and drop and TextField inside the TabControl
- Control inside TabPages (checkbox, radio, button, etc) are shown with a black background colour)
- No combobox/dropdown control.

I dont see much activity here so i guess this project doesnt have an active community.

**Comment by ubergonmx** [comment]
2nd and 3rd can be fixed manually, it is by setting the `tabControl.BackColor = Color.anycoloryouwant`
or by accessing the tabControl's property and changing it's `BackColor` (it will not change the backcolor when executed anyway so don't worry)
