### ISSUE TITLE
Font doesn't change

### ISSUE THREAD

**Issue by chpecson** [IgnaceMaes/MaterialSkin#149]
# Font doesn't change.
For example changing the font size, font family, etc in the properties, it do applies in the design view but when the code runs it ain't apply the changes in the form.

**Comment by shDiego** [comment]
The font is set in the constructor, you can overwrite the component and remove this feature.

**Comment by LiteOnE** [comment]
If you want to replace all fonts

materialSkinManager = MaterialSkinManager.Instance;
...
materialSkinManager.ROBOTO_MEDIUM_10 = new Font("font name", 10);
materialSkinManager.ROBOTO_MEDIUM_11 = new Font("font name", 11);
materialSkinManager.ROBOTO_MEDIUM_12 = new Font("font name", 12);
materialSkinManager.ROBOTO_REGULAR_11 = new Font("font name", 11);

**Comment by VahidEra** [comment]
if i want to change only one control font 
how can i do that?


i can't change any thing in material skin open Source because 
When I open it in Visual Studio is full of errors

![screenshot 2](https://cloud.githubusercontent.com/assets/27216710/25851545/6afce33e-34db-11e7-99db-991883213490.png)

**Comment by anirugu** [comment]
@VahidEra I am looking for same thing, How you managed to get it done ?

**Comment by leonelunderscore** [comment]
I encountered the same problem

**Comment by shannonfonseka** [comment]
Well I found a solution from the internet in VB language
``` vb
Dim pfc As New PrivateFontCollection
pfc.AddFontFile(Application.StartupPath & "\fnts\Roboto-Light.ttf") 'Your font location, make sure the font is in "*.ttf" format
Label1.Font = New Font(pfc.Families(0), 16) 
```

**Comment by AngelPM98** [comment]
> ROBOTO_MEDIUM_11
el ROBOTO_ ... De donde lo sacas?

**Comment by avarantes** [comment]
How can this be disabled?

**Comment by Ali4ootan** [comment]
This is also my problem!

**Comment by canekin** [comment]
how to solve pls help
