### ISSUE TITLE
Header shows old and new close out items in win 10

### ISSUE THREAD

**Issue by mach37** [IgnaceMaes/MaterialSkin#150]
Hi nice component, I followed your instructions, and below is a picture on the double heder error I am getting. Can you tell me how to resolve this.

![image](https://cloud.githubusercontent.com/assets/12221440/21757859/cfcf013a-d602-11e6-96fb-5e7ca90a2845.png)

I followed the help in the wiki page, inhereted from MaterialForm, and then initialized 
 ```var materialSkinManager = MaterialSkinManager.Instance;
      materialSkinManager.AddFormToManage(this);
      materialSkinManager.Theme = MaterialSkinManager.Themes.LIGHT;
      materialSkinManager.ColorScheme = new ColorScheme(Primary.BlueGrey800, Primary.BlueGrey900,   Primary.BlueGrey500, Accent.LightBlue200, TextShade.WHITE);```

**Comment by shDiego** [comment]
You have to set the FormBorderStyle to None;

**Comment by mach37** [comment]
@shDiego wow that nailed it! 👍 

I saw this on youtube, but looking at the code, I could not find the green or red material skins, how do I get those.
