### ISSUE TITLE
AutoSize Property Bug

### ISSUE THREAD

**Issue by SkyEngine-OSP** [IgnaceMaes/MaterialSkin#152]
There seems to be an issue with the AutoSize property on both RaisedButton and FlatButton controls.

While it is possible to turn the said property off and resize as to the developer's will. After saving and closing the form, then reopening, the property is reset to AutoSize = True and the custom size is overridden.

**Comment by ubergonmx** [comment]
I fixed it :) , I committed on my fork

**Comment by SkyEngine-OSP** [comment]
cool ! Thanks @ubergonmx
