### ISSUE TITLE
MaterialLabel text is offset by 1 character when on MaterialTabControl tab page

### ISSUE THREAD

**Issue by nommiin** [IgnaceMaes/MaterialSkin#167]
Label inside of designer
![image](https://user-images.githubusercontent.com/6483989/27701724-66023a82-5cc7-11e7-8da3-fccc1c1cadda.png)

Label on built (debug) project
![image](https://user-images.githubusercontent.com/6483989/27701776-953ab324-5cc7-11e7-8e63-c975bb42689d.png)

**Comment by nommiin** [comment]
Problem seems to be fixed by creating a "MaterialContextMenuStrip" control

**Comment by IgnaceMaes** [comment]
This issue is caused because the borders of the original tab control are removed at runtime.
