### ISSUE TITLE
[Visual Studio 2017] How to fix MaterialSkin [C# FORM]

### ISSUE THREAD

**Issue by IncVERM** [IgnaceMaes/MaterialSkin#174]
This is a way to fix your MaterialSkin in Visual Studio 2017
1. If you chose C# (Form1.cs) then double click on the form background.
2. Go and add `using MaterialSkin;` to the first line & `using System;` to the second line if you haven't already.
3. Go and change `public partial class Form1 : Form `to `public partial class Form1 : MaterialSkin.Controls.MaterialForm`
4. Go into public form1, and add these: `
            var materialSkinManager = MaterialSkin.MaterialSkinManager.Instance;
            materialSkinManager.AddFormToManage(this);
            materialSkinManager.Theme = MaterialSkin.MaterialSkinManager.Themes.DARK;
            materialSkinManager.ColorScheme = new ColorScheme(Primary.BlueGrey800, Primary.BlueGrey900, Primary.BlueGrey500, Accent.LightBlue200, TextShade.WHITE);` You may edit this later.

That's it! Your done! If you are still having any issues, please tell me and I will try to find a solution to your problem.

**Comment by weespin** [comment]
@IncVERM 
https://github.com/IgnaceMaes/MaterialSkin#implementing-materialskin-in-your-application

**Comment by IncVERM** [comment]
> @IncVERM facepalm
--
