### ISSUE TITLE
ListView first column erro

### ISSUE THREAD

**Issue by mtayllan** [IgnaceMaes/MaterialSkin#193]
When the item has much characters, it overlaps the next columns.
Instead, the item should be cut and put in the end "..." just like the other columns!
![print](https://user-images.githubusercontent.com/33026097/34835154-c20c6f50-f6d2-11e7-8ed1-383a84d95bd0.PNG)

**Comment by Zerglrisk** [comment]
You have to Empty First Item.

make a columnheader and set fist columnheader. and than set width 0 and text empty.

    string[] row = {"", ap.Name, ap.SignalStrength.ToString()};
    var item = new ListViewItem(row);
    lv_Wireless.Add(item);
