### ISSUE TITLE
SingleLineTextField events not firing

### ISSUE THREAD

**Issue by IgnaceMaes** [IgnaceMaes/MaterialSkin#20]
The problem is that MaterialSingleLineTextField is just a holder for a base textbox, but of the type of Control. It draws the onfocus animation. To catch the events from the TextBox itself you would have to subscribe to the events of the base TextBox in it.

**Comment by AlexxEG** [comment]
You could perhaps just forward the event registering to the TextBox using this:

http://tech.pro/tutorial/696/csharp-tutorial-event-accessors

```chsarp
public event EventHandler SomeEvent
{
    add
    {
        TextBox.SomeEvent += value;
    }
    remove
    {
        TextBox.SomeEvent -= value;
    }
}
```

And then if the Control part needs to react to some event, it can subscribe to the event from the TextBox. You'll probably have to do it for each event though.

**Comment by IgnaceMaes** [comment]
It would require a lot of code if we have to forward all events like that. Though, it would probably be the best solution.

Making the base TextBox public would be a lazy solution, but this wouldn't be logical for someone who's just using the skin and doesn't know.

**Comment by AlexxEG** [comment]
I might have a alternative method that I will look more into tomorrow, but I'm not sure if it will work.

Here are all the events if you want, taken from the BaseTextBox class so all the TextBox specific events are there also: http://pastebin.com/wZ1n2tN6

Maybe wrap them in a \#region?

```c#
#region Forwarded events
...
#endregion
```

Or something like that.

**Comment by IgnaceMaes** [comment]
Thank you @AlexxEG for the code. I've put it in a region as suggested.
It works perfectly fine now!

**Comment by AlexxEG** [comment]
No problem. :)

The alternative method didn't work by the way.
