### ISSUE TITLE
Have A Way To Make Material Skin To Supporting .NET Framework 4?

### ISSUE THREAD

**Issue by HowToDoThis** [IgnaceMaes/MaterialSkin#201]
Due **Windows XP** Supported To **.NET Framework 4 Only**, So Does It Have A Way To Make **MaterialSkin** Supporting **.NET Framework 4**?

Because We Have **Windows XP** User, So We Need To Make It Supporting **Windows XP**.

**Comment by DarkByte7** [comment]
How to: Target a Version of the .NET Framework: [MSDN](https://msdn.microsoft.com/en-us/library/bb398202.aspx)
