### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by anirudhagupta** [IgnaceMaes/MaterialSkin#207]
Despite everyone is busy, I don't see replied on new thread(s). I am trying to set a background color to label

0,215,79,41 but it show red and when I close open it's show the same color.

Does this many  time, nothing work. I am seeing that close (3 top button in right) is hiding behind  the top panel.

Listview show the scrollbar which I didn't find the way to fix. 

Is this project dead or I am missing something here.

**Comment by anirugu** [comment]
@SaitDev  ok, got it.

**Comment by brinehart** [comment]
@SaitDev @IgnaceMaes  Is there anyone currently handling the open PRs and updating the Nuget packages? There are some great community provided features there but not sure if anyone is able to push them into master and update the nuget packages.

**Comment by anirudhagupta** [comment]
@brinehart He is busy and will not replied, I have opened 9 issues here, if he have time he certainly closed it. I see his linkedin profile 1-2 months ago and it's look like he is doing some kind of work (maybe mobile).

**Comment by SaitDev** [comment]
Im not maintainer of the project, i cant push nor public nuget package
