### ISSUE TITLE
Is there any way to set the border in MaterialSkin Window.

### ISSUE THREAD

**Issue by anirugu** [IgnaceMaes/MaterialSkin#211]
Is there any property that can be used to show border on the screen.

**Comment by OpM3TA** [comment]
Another issue is even if you have an item FILLING the form, the theme causes so much "empty" space especially like at the bottom. Currently have a tab control filling the form and the amount of space at the bottom makes everything look like trash.

I'm worried this is a long dead project its time for users to take it up I guess.

**Comment by anirugu** [comment]
I like that someone @IgnaceMaes  take his time and implement this project. I use it on an 8-9 project that all based on WinForms. The software was shipped but it does take a lot of work that I don't think is required to produce that thing.

I moved from this dead project to https://github.com/material-components/material-components-web 
which is supported by Google, Now use IE11 for web browser control and I can use my same HTML skill on web and desktop.

Why waste my time on this project when it's not supported (no offense) and I can get a better result from Google supported material supported component. At least they will give me a notice or better thing to move on, (instead of provide no-support).

I am not blaming here the developer but it was never going well. I use it on 8-9 project and I have wasted a lot of time.

The theme limitation (you can't set the font for 2 different labels or 2 different colors), I write my own code to sort out this issue)

Late on I find that If I us my html skill I can better same skill for everything (web and mobile).

If anyone looking for a sollution or alternative, I can suggest you IE11 based web browser control in winforms is good to go with this repos

https://github.com/material-components/material-components-web

If you can afford or force your user to use 1803 (latest window update) you can use WebView which Microsoft released last month at build.
