### ISSUE TITLE
Is it possible to disable resizing the borders?

### ISSUE THREAD

**Issue by ThaisenPM** [IgnaceMaes/MaterialSkin#237]
I was hoping to make it so my MaterialSkin form can't be resized like this base WinForm.
Notice how I cannot even select the side here for resizing: https://i.imgur.com/QkQqO3C.gifv

No matter what I do, either I end up having the base WinForm border or I can still resize the window
(Base WinForm Border)
This is what I end up with while setting the border style to FixedSingle: https://i.imgur.com/dFIm1Sp.gifv

(this.FormBorderStyle = FormBorderStyle.None;)
And another method that normally doesn't allow resizing but this library does: https://i.imgur.com/Vuttl3B.gifv

I was thinking about just making another thread that checks the form size and resets it if it does not match what needed. Is there a way to do this without making extra threads OR is that my only option?

Edit:
I added another thread to fix the size if it got changed. This was the result: https://i.imgur.com/3X5opOH.gifv

**Comment by ebrahimelsayed98** [comment]
Go to (Form1) Properties > Misc > Sizable = False
OR
```
public form1()
{
    InitializeComponent();
     Sizable = false;
}
```
That is all.
Have a nice day.

**Comment by hmz777** [comment]
weird this doesn't happen to me at all like ebrahim said `Sizable = false` does the trick
[See my form](https://i.imgur.com/yeNyh9f.gifv)
