### ISSUE TITLE
Adding Material Single Line Text Box to a Material Tab produces an Error

### ISSUE THREAD

**Issue by TheDeadPhoenix** [IgnaceMaes/MaterialSkin#24]
I was attempting to add a Material Line Text Box to a Material Tab and Visual Studio produced the following Error:

Control does not support transparent background colors.

Thanks,

**Comment by AlexxEG** [comment]
Are your text box background transparent? Or the material tab that's it's in?

**Comment by TheDeadPhoenix** [comment]
Apparently the default was set to transparent. Changing it to white did resolve that problem. 

Thanks,

**Comment by AlexxEG** [comment]
No problem. :)

@IgnaceMaes Can probably close this now. :)
