### ISSUE TITLE
materialtabselector Error After Delete item From Tabcontrollers

### ISSUE THREAD

**Issue by Alephgsm** [IgnaceMaes/MaterialSkin#241]
hi 
i use Materialskin in my project
The big problem we are facing is that material tabselector 
we showing This Error After delete a tabpage from tabcontroler
![1398-03-21 21_14_54-OverlayControl](https://user-images.githubusercontent.com/33460603/59560319-7acdad00-9025-11e9-99f7-8f16079bd74d.png)
I even delete it(tabselector) and add again . Unfortunately, show again This Error after Select basetabcontrol
tab selector is not a problem with other tabcontrols

Please Help 
Thanks for the best

**Comment by iliyasoori** [comment]
Help Please
