### ISSUE TITLE
Glitchy text in MaterialComboBox

### ISSUE THREAD

**Issue by marcguillemdev** [IgnaceMaes/MaterialSkin#255]
Hi guys, im using this library for my C# project and all works fine except the MaterialComboBox.

The text seems fine, but if i move the mouse over the items the text is being glitchy.

Lastest version of Visual Studio and Windows.

![proof1](https://user-images.githubusercontent.com/30577118/91177344-ddb7db00-e6e3-11ea-9f88-668a2bf32685.PNG)
![proof2](https://user-images.githubusercontent.com/30577118/91177342-dd1f4480-e6e3-11ea-9ced-0dcafbfa8c6c.PNG)

Thanks in advance. Keep doing this awesome library! 👍

**Comment by Stefangansevles** [comment]
I'm having the same issue :(
but yeah this library is 100% AWESOME
