### ISSUE TITLE
The font doesn't change size.

### ISSUE THREAD

**Issue by matteoturini** [IgnaceMaes/MaterialSkin#256]
MaterialLabel: can't change font size, it doesn't work.

**Comment by Stefangansevles** [comment]
I think it's not supposed to, it's supposed to use the material design standards. You can still change the label's size by picking a different mode, h1, h2, etc. theres a bunch of different things to pick from

**Comment by shannonfonseka** [comment]
Well I found a solution from the internet in VB language
``` vb
Dim pfc As New PrivateFontCollection
pfc.AddFontFile(Application.StartupPath & "\fnts\Roboto-Light.ttf") 'Your font location, make sure the font is in "*.ttf" format
Label1.Font = New Font(pfc.Families(0), 16) 
```

**Comment by matteoturini** [comment]
Actually, you need to change the font's type. I found this way too late, and it needs to be on the docs. There are different font types with different sizes and colors.

**Comment by Zymowski** [comment]
But how to change font type for particular label ?
