### ISSUE TITLE
Mainform crashed when using Password Property

### ISSUE THREAD

**Issue by L-Dlbcq** [IgnaceMaes/MaterialSkin#273]
Hello,

I'm developing a password manager and i encounter problem with it. As you can see in the following [gif](https://gifyu.com/image/SLdos), I'm using a database file encrypted by password and i set a button to show the passwords. But if I cancel this, my principal window is crashing. Does someone encounter a similar problem ? Does exists a solution ?

Sorry for my bad english

**Comment by AndersTuomainen** [comment]
Had same issue with MaterialTextBox so I had to change to MaterialMaskedTextBox and use passwordChar property

**Comment by L-Dlbcq** [comment]
It works
