### ISSUE TITLE
MaterialForm should respect its properties

### ISSUE THREAD

**Issue by IgnaceMaes** [IgnaceMaes/MaterialSkin#33]
MaterialForm currently doesn't respect a few of the properties that a Form has:
- Be able to block forms from being resized
- Be able to block forms from maximizing/minimizing
- Show or hide the ControlBox

**Comment by aldoblack** [comment]
You can do another trick until this method is updated. You can set MinimumSize and MaximumSize the same as window Size. This should do the trick.
But when you click on Maximize Box the windows is positioned on top right corner of monitor.

**Comment by IgnaceMaes** [comment]
MaterialForm now respects all its properties listed here, hooray!
