### ISSUE TITLE
WndProc &HF030&

### ISSUE THREAD

**Issue by NoobTW** [IgnaceMaes/MaterialSkin#45]
I tried to catch the maximize event but failed.
Also I can't disable control box and buttons.

**Comment by IgnaceMaes** [comment]
Are you using the NuGet package? This should be fixed in the project, but I simply haven't pushed the update to NuGet yet.

**Comment by NoobTW** [comment]
Yes, I am using NuGet package. Maybe I should wait for your updates or compile your source on my own, right?
Thanks in advanced.

**Comment by IgnaceMaes** [comment]
Sorry for the delay, but MaterialSkin 0.2.1 has been pushed to NuGet. (Including the ability to disable the control box buttons)
