### ISSUE TITLE
is there a way to add image or background image to a button

### ISSUE THREAD

**Issue by kim24** [IgnaceMaes/MaterialSkin#46]
I tried to add a picture to the raised button but it doesn't work is there a solution for that ?

**Comment by DarkKnightKirito** [comment]
Download source code and make your own "MaterialDesignImageButton"
Or if you want to wait you can tell author to make one.
W dniu śr., 29 kwi 2015 o 15:06 akimu13 <notifications@github.com>
napisał(a):

**Comment by IgnaceMaes** [comment]
There currently is no way of doing this in the official build, and I'm also not planning to support it as it isn't specified in Google's Material Design Principles.

As said by DarkKinightKirito, you could fork the project and make one yourself. I wouldn't be that difficult.

**Comment by hishaamn** [comment]
Hi,
I am currently new to User Control. I need to add icon to the button. Can you please help me out on how to achieve this?

Thanks
