### ISSUE TITLE
Different Theme Across Forms

### ISSUE THREAD

**Issue by tytanmcbride** [IgnaceMaes/MaterialSkin#47]
Is there no way to have a different theme across different forms/windows?

**Comment by IgnaceMaes** [comment]
No, this isn't possible.

I've made the SkinManager a singleton because I found it logical you'd use the same look and feeling in your whole application. Do you have a specific need for this?

**Comment by tytanmcbride** [comment]
I see what you were going for, I ended up finding something that works, just needed to fine-tune the colours I guess to my liking! By the way, love what you've done with this!
