### ISSUE TITLE
How do you update the form title?

### ISSUE THREAD

**Issue by mouse0270** [IgnaceMaes/MaterialSkin#66]
I am updating an application to use this form design, but when I try to update the form title I don't see the change. It seems to always stay the same as when the application was launched.

**Comment by jcaruso001** [comment]
Are you talking about at the top of the form, see screenshot...

![image](https://cloud.githubusercontent.com/assets/4194148/8938405/1dd6cd6c-3524-11e5-8b44-78c0ab36dd91.png)

**Comment by mouse0270** [comment]
Yes, and nevermind. It is 95 in my office because the AC is out and I made a huge noob mistake. I was chaning `name` instead of `text`. I really hate the hot weather.
