### ISSUE TITLE
Unable to run on .NET4

### ISSUE THREAD

**Issue by mr-lanholmes** [IgnaceMaes/MaterialSkin#69]
Tried to run on .net4 but it keeps saying missing library/reference. I reinstalled the reference from nuget but doesnt solve the problem. 

Thanks

**Comment by hadyfayed** [comment]
OK i am new here but i know that if you install a nuget package then changed the frame work you have to remove the reference and then install the package again , plus it will help if you shared a screenshot

**Comment by mr-lanholmes** [comment]
![mskin](https://cloud.githubusercontent.com/assets/2654430/9038458/f4127780-3a26-11e5-83b6-3b6259b46a18.JPG)

cc. @hadyfayed 

This is screenshot. Tried to remove everything, and reinstall from nuget but doesnt solve the problem.

Thanks.

**Comment by lukeskinner** [comment]
When I try this on a .NET 4 project I get this error - not sure why you don't see the full error: 
```
The primary reference "MaterialSkin" could not be resolved because it was built against the ".NETFramework,Version=v4.5" framework. 
This is a higher version than the currently targeted framework ".NETFramework,Version=v4.0,Profile=Client"/		
```

Looking at https://github.com/IgnaceMaes/MaterialSkin/blob/master/MaterialSkin/MaterialSkin.csproj it uses .NET 4.5 so it is incompatible with .NET 4.0 projects for the time being.
```
<TargetFrameworkVersion>v4.5</TargetFrameworkVersion>
```

**Comment by mr-lanholmes** [comment]
Thanks!
