### ISSUE TITLE
materialCheckBox.Checked always defaults to false

### ISSUE THREAD

**Issue by Lucidator** [IgnaceMaes/MaterialSkin#71]
My materialCheckBox1.Checked always defaults to false, even when it is checked. I'm using as a "have you accepted Terms and Conditions" with a simple IF. I cannot get the if to run the main code that should happen when you accept terms and conditions, it only runs the "please accept terms and conditions" code.

            if(materialCheckBox1.Checked == true)
            {
                
            }
            else
            {
                MessageBox.Show("You cannot install " + Resources.ResourceManager.GetString("modname") + " without accepting the Terms and Conditions.");
            }

**Comment by MikeGWem** [comment]
The materialCheckBox checked state works just fine in my testing. While I would have written the "if" slightly differently 
`if(materialCheckBox1.Checked)`
skipping the redundant "== true" the code is just fine as it is.
The most likely answer is that materialCheckBox1, in your case, is not the Checkbox you think it is.

**Comment by IgnaceMaes** [comment]
I recommend you renaming your controls so you do know you're checking the right one.
