### ISSUE TITLE
ListView for Windows Form in VB Net

### ISSUE THREAD

**Issue by isdzulqor** [IgnaceMaes/MaterialSkin#85]
I see in your documentation that Material Listview is included. But I didn't find it in my Material toolbox component in VB NET. Could you tell me more about material listview in Windows Form VB net

**Comment by GreenTurtwig** [comment]
Also the progress bar. :-)

**Comment by StephanBis** [comment]
I think you need to manually download the git files, the NuGet package isn't updated I think

**Comment by isdzulqor** [comment]
@StephanBis how to add library manually from git,, Could you tell me more, please.. Iam new in VB net..

**Comment by StephanBis** [comment]
@isdzulqor 
1) Open the .sln that you download from here
2) Rebuild the solution
3) Open your own .NET project where you want to use MaterialSkin
4) Right click references and press Add, now browse to the bin/debug folder of the downloaded solution and select MaterialSkin.dll (you can do the same for your toolbox items)
5) You can now use MaterialSkin

**Comment by isdzulqor** [comment]
@StephanBis Thanks bro, I'll try it
