### ISSUE TITLE
How to Change Font?

### ISSUE THREAD

**Issue by AlphaBs** [IgnaceMaes/MaterialSkin#94]
I try to change the font.
![1](https://cloud.githubusercontent.com/assets/17783561/13703018/0c4cf944-e7d6-11e5-9f3a-ab360fda0f52.PNG)

But It dosen't Changed.
![2](https://cloud.githubusercontent.com/assets/17783561/13703022/10016458-e7d6-11e5-8286-058d8cbf0222.PNG)

How can I Change Font?

**Comment by SaitDev** [comment]
modified the source of RaisedButton

**Comment by yejinmo** [comment]
![qq 20160312110542](https://cloud.githubusercontent.com/assets/14041047/13720404/ba95118c-e842-11e5-8100-703f37cb578f.jpg)
![qq 20160312110525](https://cloud.githubusercontent.com/assets/14041047/13720403/b4d5b94a-e842-11e5-9250-97eadc81f94e.jpg)

**Comment by AlphaBs** [comment]
Thank You!

**Comment by SaitDev** [comment]
@yejinmo that method will change font of all other material controls
