### ISSUE TITLE
Spyware.Pony

### ISSUE THREAD

**Issue by Mmatiasn** [IgnaceMaes/MaterialSkin#98]
I've downloaded the project and added to my project. Now I'm getting Spyware.Pony found in Assembly alerts from Malware-bytes, don't download this project...

**Comment by lukeskinner** [comment]
I just did a scan of the latest NuGet package v0.2.1 and it came back clean on the Virus Total scanner including Malwarebytes.

https://www.virustotal.com/en/file/a843049e9fc1fbd01983aab97fa766332acdab8ccf5c369b00d2def56df37db6/analysis/1459024727/

Did you add MaterialSkin to your project via NuGet or did you download the zip from GitHub? Either way neither should have reference to any spyware.

My guess would be one of the following:
1. It's a false positive
2. You have something else in your assembly that's suspicious 
3. Your computer which is building the code is already infected with something

**Comment by Mmatiasn** [comment]
It's a clean version of windows 10 and I downloaded it as a zrip from Github. Let me take a second look but I have not added anything to this project but the  materialskin.dll

**Comment by DarkKnightKirito** [comment]
If you feel suspicious about this project, just check code before running
it. I myself have downloaded this project scanned(with malwarebytes,
kaspersky and virustotal) and it was 100% clean. I was running project many
times and I did run project many times. Maybe your Windows 10 is downloaded
from untrusted source? Anyways project its safe and you dont need to panic.

sob., 26 mar 2016, 23:05 użytkownik Mmatiasn <notifications@github.com>
napisał:

**Comment by Mmatiasn** [comment]
I came to the conclusion that I was not able to determine the source of spyware.pony . I'll update this if I find anything out.

**Comment by IgnaceMaes** [comment]
Closing this issue. Everything is open source, kind of ridiculous to call spyware.

Make sure you only download from the official GitHub page and the NuGet (linked in the project's README).
