### ISSUE TITLE
.Net Framework 4.0

### ISSUE THREAD

**Issue by JasonHK** [IgnaceMaes/MaterialSkin#99]
Would you add the support of .Net Framework 4.0?

**Comment by MikeGWem** [comment]
What does not work with .NET 4 or what are you looking to have added?

I am using this with .NET 4.52 with no .NET issues at the moment.

**Comment by lukeskinner** [comment]
MaterialSkin currently uses .NET 4.5 which means you have to target .NET 4.5 or higher to use this library.

Pull request #93 back ports MaterialSkin to .NET 2.0 so this PR would resolve this.

**Comment by MikeGWem** [comment]
Hi Luke, OK I now understand. I started from the position of expecting any developer to download the source and work from there - can't imagine not wanting to tweak and try and sort out any bugs arising from **my** particular use case.

Example: Checkboxes fill with the Accent colour while I think they look better in the DarkPrimary - I can make that small tweak and then decide if I should offer some code to provide an option (still mulling that one)

**Comment by JasonHK** [comment]
@lukeskinner Thanks your help!
